const express = require("express");
const router = express.Router();
const DiscountsController = require("../controllers/DiscountsController");
router.get('/sales/all', DiscountsController.getAllDiscounts);
router.post('/sales/add', DiscountsController.addDiscount);
router.put('/sales/:id', DiscountsController.updateDiscount);
router.delete('/sales/:id', DiscountsController.deleteDiscount);
router.delete('/sales/delete-expired', DiscountsController.deleteExpiredDiscounts);
router.delete('/sales/delete-inactive', DiscountsController.deleteInactiveDiscounts);
router.get('/sales/search', DiscountsController.searchDiscounts);
router.get('/personalized-offers/all', DiscountsController.getAllPersonalizedOffers);
router.post('/personalized-offers/add', DiscountsController.addPersonalizedOffer);
router.put('/personalized-offers/:id', DiscountsController.updatePersonalizedOffer);
router.delete('/personalized-offers/:id', DiscountsController.deletePersonalizedOffer);
router.get('/personalized-offers/search', DiscountsController.searchPersonalizedOffers);
router.get('/stats', DiscountsController.getDiscountsStats);
router.get('/users', DiscountsController.getUsers);
router.get('/tours', DiscountsController.getTours);
router.get('/flights', DiscountsController.getFlights);
router.get('/airlines', DiscountsController.getAirlines);
router.get('/user-bookings/:userId', DiscountsController.getUserBookings);
module.exports = router;